export const eventTypes = [
  "actor.registered",
  "actor.revoked",
  "actor.tokenRotated",
  "lease.claimed",
  "lease.released",
  "lease.renewed",
  "node.awaitingApproval",
  "node.created",
  "node.deleted",
  "node.discarded",
  "node.done",
  "node.imported",
  "node.partial",
  "node.pending",
  "node.ready",
  "node.running",
  "node.unblocked",
  "node.updated",
  "outcome.reported",
  "plan.imported",
  "project.created",
  "project.repositoriesReplaced",
  "provider.defaultSet",
  "provider.defaultUnset",
  "provider.registered",
  "provider.removed",
  "provider.renamed",
  "recovery.childReaped",
  "recovery.journalReconciled",
  "recovery.leaseBlocked",
  "recovery.leaseRecovered",
  "recovery.publishReconcilePending",
  "recovery.remnantRefused",
  "recovery.remnantRemoved",
  "repository.outsideWriter",
  "repository.register.credentialRejected",
  "repository.registered",
] as const;

export type EventType = (typeof eventTypes)[number];

export const retiredEventTypes: readonly EventType[] = [];
