import { nodeStates } from "./state.ts";
import type { NodeKind, NodeState } from "./state.ts";

export type TransitionRow = Readonly<{
  from: NodeState;
  to: NodeState;
  task: boolean;
  objective: boolean;
  initiative: boolean;
  note: string;
}>;

export const transitions: readonly TransitionRow[] = [
  {
    from: "pending",
    to: "ready",
    task: true,
    objective: true,
    initiative: true,
    note: "Every dependency is `done` or `partial`. The scheduler writes it.",
  },
  {
    from: "pending",
    to: "running",
    task: false,
    objective: false,
    initiative: false,
    note: "A claim reads `ready`. `ready` is the proof that every dependency is satisfied.",
  },
  {
    from: "pending",
    to: "blocked",
    task: true,
    objective: true,
    initiative: true,
    note: "A dependency is discarded, reason `dependency-discarded`. T: also `abandon objective`, reason `abandoned`.",
  },
  {
    from: "pending",
    to: "awaiting_approval",
    task: false,
    objective: false,
    initiative: false,
    note: "The gate needs a frozen candidate, and no work ran.",
  },
  {
    from: "pending",
    to: "done",
    task: false,
    objective: false,
    initiative: false,
    note: "No check result exists.",
  },
  {
    from: "pending",
    to: "partial",
    task: false,
    objective: false,
    initiative: false,
    note: "Aggregation leaves `running`, and no child started.",
  },
  {
    from: "pending",
    to: "discarded",
    task: true,
    objective: true,
    initiative: true,
    note: "Human discard. The subtree holds no commit.",
  },
  {
    from: "ready",
    to: "pending",
    task: false,
    objective: false,
    initiative: false,
    note: "An abandon parks the node in `blocked`. Only import and `unblock` write `pending`.",
  },
  {
    from: "ready",
    to: "running",
    task: true,
    objective: true,
    initiative: true,
    note: "T: the worker starts the attempt. O: a worker claims the objective lease. I: the first objective starts.",
  },
  {
    from: "ready",
    to: "blocked",
    task: true,
    objective: true,
    initiative: true,
    note: "A dependency is discarded, reason `dependency-discarded`. A discard blocks every dependent, whatever its state. T and O: also an abandon, reason `abandoned`.",
  },
  {
    from: "ready",
    to: "awaiting_approval",
    task: false,
    objective: false,
    initiative: false,
    note: "The gate needs a frozen candidate, and no work ran.",
  },
  {
    from: "ready",
    to: "done",
    task: false,
    objective: false,
    initiative: false,
    note: "No check result exists.",
  },
  {
    from: "ready",
    to: "partial",
    task: false,
    objective: false,
    initiative: false,
    note: "Aggregation leaves `running`.",
  },
  {
    from: "ready",
    to: "discarded",
    task: true,
    objective: true,
    initiative: true,
    note: "Human discard. The subtree holds no commit.",
  },
  {
    from: "running",
    to: "pending",
    task: false,
    objective: false,
    initiative: false,
    note: "An abandon parks the node in `blocked`. Only import and `unblock` write `pending`.",
  },
  {
    from: "running",
    to: "ready",
    task: true,
    objective: false,
    initiative: false,
    note: "T: recovery finds an expired lease, a clean tree, and the head at the base. O and I: no operation rewinds a running parent to a claimable state.",
  },
  {
    from: "running",
    to: "blocked",
    task: true,
    objective: true,
    initiative: true,
    note: "T: `attempt-limit`, `dirty-recovery` on an expired lease over a dirty tree, or `abandoned`. O: `abandoned`. I: `e2e-failed`. `stale-base` arises at integration, which runs from `awaiting_approval`.",
  },
  {
    from: "running",
    to: "awaiting_approval",
    task: false,
    objective: true,
    initiative: false,
    note: "O: every task is terminal, and at least one task is `done`. T and I: the gate is objective only.",
  },
  {
    from: "running",
    to: "done",
    task: true,
    objective: false,
    initiative: true,
    note: "T: `re@1` accepts the diff. I: every objective is `done`, and the end-to-end check passed or recorded `not-applicable`. O: an objective always passes the human gate.",
  },
  {
    from: "running",
    to: "partial",
    task: false,
    objective: false,
    initiative: true,
    note: "I: every objective is terminal, at least one is `done`, at least one is `discarded`, and the end-to-end check passed or recorded `not-applicable`. T: a task has no child. O: an objective always passes the human gate.",
  },
  {
    from: "running",
    to: "discarded",
    task: false,
    objective: true,
    initiative: true,
    note: "O and I: every child is `discarded`, or a human discards a subtree that holds no commit. T: the task holds a live lease and may hold commits. Abandon it first.",
  },
  {
    from: "blocked",
    to: "pending",
    task: true,
    objective: true,
    initiative: true,
    note: "`unblock` clears `attempt-limit`, `dirty-recovery`, `stale-base` and `abandoned`. `dependency-discarded` needs `waive`, or a re-import that rewires the edge. `e2e-failed` clears when the repair objective imports.",
  },
  {
    from: "blocked",
    to: "ready",
    task: false,
    objective: false,
    initiative: false,
    note: "`unblock` writes `pending`, and the scheduler re-derives readiness. A cleared node whose dependency is still discarded must not become claimable.",
  },
  {
    from: "blocked",
    to: "running",
    task: false,
    objective: false,
    initiative: false,
    note: "`unblock` writes `pending`, and the scheduler re-derives eligibility before any claim.",
  },
  {
    from: "blocked",
    to: "awaiting_approval",
    task: false,
    objective: false,
    initiative: false,
    note: "No approved candidate exists.",
  },
  {
    from: "blocked",
    to: "done",
    task: false,
    objective: false,
    initiative: false,
    note: "The check that blocked it never passed.",
  },
  {
    from: "blocked",
    to: "partial",
    task: false,
    objective: false,
    initiative: false,
    note: "Aggregation leaves `running`.",
  },
  {
    from: "blocked",
    to: "discarded",
    task: true,
    objective: true,
    initiative: true,
    note: "Human discard, when the subtree holds no commit. The human abandons first in every other case.",
  },
  {
    from: "awaiting_approval",
    to: "pending",
    task: false,
    objective: false,
    initiative: false,
    note: "An abandon parks the objective in `blocked`. Only import and `unblock` write `pending`.",
  },
  {
    from: "awaiting_approval",
    to: "ready",
    task: false,
    objective: false,
    initiative: false,
    note: "An abandon parks the objective in `blocked`, so a human decides before the objective runs again.",
  },
  {
    from: "awaiting_approval",
    to: "running",
    task: false,
    objective: false,
    initiative: false,
    note: "Every task is already terminal, and a claim reads `ready`.",
  },
  {
    from: "awaiting_approval",
    to: "blocked",
    task: false,
    objective: true,
    initiative: false,
    note: "O: integration hit a content conflict, or the merge retry limit, reason `stale-base`. Also `abandon objective`, reason `abandoned`.",
  },
  {
    from: "awaiting_approval",
    to: "done",
    task: false,
    objective: true,
    initiative: false,
    note: "O: a human approved the frozen candidate, integration succeeded, and every task is `done`.",
  },
  {
    from: "awaiting_approval",
    to: "partial",
    task: false,
    objective: true,
    initiative: false,
    note: "O: as `done`, and the approval carried `acknowledge_partial`.",
  },
  {
    from: "awaiting_approval",
    to: "discarded",
    task: false,
    objective: false,
    initiative: false,
    note: "The candidate holds commits. The human abandons the objective first, then discards it from `blocked`.",
  },
  {
    from: "done",
    to: "pending",
    task: false,
    objective: false,
    initiative: false,
    note: "Terminal, except for the task row above.",
  },
  {
    from: "done",
    to: "ready",
    task: false,
    objective: false,
    initiative: false,
    note: "Terminal, except for the task row above.",
  },
  {
    from: "done",
    to: "running",
    task: false,
    objective: false,
    initiative: false,
    note: "Terminal, except for the task row above.",
  },
  {
    from: "done",
    to: "blocked",
    task: true,
    objective: false,
    initiative: false,
    note: "T: an abandon resets the workspace, so the commits behind the `done` verdict disappear. Reason `abandoned`. O and I: a `done` parent is integrated.",
  },
  {
    from: "done",
    to: "awaiting_approval",
    task: false,
    objective: false,
    initiative: false,
    note: "Terminal, except for the task row above.",
  },
  {
    from: "done",
    to: "partial",
    task: false,
    objective: false,
    initiative: false,
    note: "Terminal, except for the task row above.",
  },
  {
    from: "done",
    to: "discarded",
    task: false,
    objective: false,
    initiative: false,
    note: "Terminal, except for the task row above.",
  },
  {
    from: "partial",
    to: "pending",
    task: false,
    objective: false,
    initiative: false,
    note: "Terminal. `acknowledge_partial` records a human decision at approval time, and it writes no transition out of `partial`.",
  },
  {
    from: "partial",
    to: "ready",
    task: false,
    objective: false,
    initiative: false,
    note: "Terminal. `acknowledge_partial` records a human decision at approval time, and it writes no transition out of `partial`.",
  },
  {
    from: "partial",
    to: "running",
    task: false,
    objective: false,
    initiative: false,
    note: "Terminal. `acknowledge_partial` records a human decision at approval time, and it writes no transition out of `partial`.",
  },
  {
    from: "partial",
    to: "blocked",
    task: false,
    objective: false,
    initiative: false,
    note: "Terminal. `acknowledge_partial` records a human decision at approval time, and it writes no transition out of `partial`.",
  },
  {
    from: "partial",
    to: "awaiting_approval",
    task: false,
    objective: false,
    initiative: false,
    note: "Terminal. `acknowledge_partial` records a human decision at approval time, and it writes no transition out of `partial`.",
  },
  {
    from: "partial",
    to: "done",
    task: false,
    objective: false,
    initiative: false,
    note: "Terminal. `acknowledge_partial` records a human decision at approval time, and it writes no transition out of `partial`.",
  },
  {
    from: "partial",
    to: "discarded",
    task: false,
    objective: false,
    initiative: false,
    note: "Terminal. `acknowledge_partial` records a human decision at approval time, and it writes no transition out of `partial`.",
  },
  {
    from: "discarded",
    to: "pending",
    task: false,
    objective: false,
    initiative: false,
    note: "Terminal. An abandon skips a discarded task, because the discard carries a human reason.",
  },
  {
    from: "discarded",
    to: "ready",
    task: false,
    objective: false,
    initiative: false,
    note: "Terminal. An abandon skips a discarded task, because the discard carries a human reason.",
  },
  {
    from: "discarded",
    to: "running",
    task: false,
    objective: false,
    initiative: false,
    note: "Terminal. An abandon skips a discarded task, because the discard carries a human reason.",
  },
  {
    from: "discarded",
    to: "blocked",
    task: false,
    objective: false,
    initiative: false,
    note: "Terminal. An abandon skips a discarded task, because the discard carries a human reason.",
  },
  {
    from: "discarded",
    to: "awaiting_approval",
    task: false,
    objective: false,
    initiative: false,
    note: "Terminal. An abandon skips a discarded task, because the discard carries a human reason.",
  },
  {
    from: "discarded",
    to: "done",
    task: false,
    objective: false,
    initiative: false,
    note: "Terminal. An abandon skips a discarded task, because the discard carries a human reason.",
  },
  {
    from: "discarded",
    to: "partial",
    task: false,
    objective: false,
    initiative: false,
    note: "Terminal. An abandon skips a discarded task, because the discard carries a human reason.",
  },
] as const;

const lookup = new Map<string, TransitionRow>(
  transitions.map((row) => [`${row.from}->${row.to}`, row]),
);

export function canTransition(
  level: NodeKind,
  from: NodeState,
  to: NodeState,
): boolean {
  if (from === to) return false;
  const row = lookup.get(`${from}->${to}`);
  return row ? row[level] : false;
}
