import type { ScenarioId } from "../tag.ts";
import { harnessTaskAssertionNames } from "./harness.ts";

export const journeyAssertionNames: readonly string[] = [
  "no-config-exit",
  "no-config-names-search-order",
  "first-location-starts",
  "version-parity",
  "credential-registered",
  "repository-registered",
  "ref-layout",
  "project-created",
  "repository-bound",
  "plan-imported",
  "export-byte-identical",
  "reimport-same-revision",
  "reimport-choices-suggested",
  "reimport-stale-revision",
  "status-counts",
  "run-not-implemented",
  "status-unchanged",
];

export const fixtureProfileAssertionNames: readonly string[] = [
  "fixture-head-symref",
  "fixture-fetch",
  "fixture-receive-pack-refuses-wrong-token",
];

export const transportAssertionNames: readonly string[] = [
  "no-token-status",
  "no-token-code",
  "wrong-token-status",
  "wrong-token-code",
  "origin-header-status",
  "origin-header-code",
  "foreign-host-status",
  "foreign-host-code",
  "absent-host-status",
  "absent-host-code",
  "allowed-host-status",
];

export const disclosureAssertionNames: readonly string[] = [
  "no-disclosure-bearer-header",
  "no-disclosure-basic-header",
  "no-disclosure-config",
  "no-disclosure-printed-commands",
  "no-disclosure-daemon-logs",
  "no-disclosure-podman-inspect",
  "no-disclosure-diagnostics",
  "no-disclosure-config-mode",
];

export const expectedAssertions: Readonly<
  Record<ScenarioId, readonly string[] | "non-empty">
> = {
  "P1-E1": "non-empty",
  "P1-E2": "non-empty",
  "P1-E4": "non-empty",
  "P1-E5": "non-empty",
  "P1B-E1": [
    ...fixtureProfileAssertionNames,
    ...journeyAssertionNames,
    "transient-create-status",
    "transient-create-completeness",
    "transient-node-revision",
    "transient-update-status",
    "transient-update-completeness",
    "transient-update-title",
    "transient-delete-status",
    "transient-delete-completeness",
    "transient-delete-identity",
    "transient-gone",
    "export-revision-after-delete",
    "export-documents-after-delete",
    "durable-create-status",
    "durable-create-completeness",
    "authored-edges-unchanged",
    "durable-state-ready",
    "transient-event-types",
    "transient-event-actor",
    "durable-event-types",
    "durable-event-actor",
    "authoring-operation-ids",
    "ready-frontier",
    "alpha-1-claim-status",
    "alpha-1-claim-attempt",
    "alpha-1-heartbeat-status",
    "alpha-1-report-status",
    "alpha-1-state",
    "alpha-2-claim-status",
    "alpha-2-claim-attempt",
    "alpha-2-heartbeat-status",
    "alpha-2-report-status",
    "alpha-2-state",
    "alpha-authored-claim-status",
    "alpha-authored-claim-attempt",
    "alpha-authored-heartbeat-status",
    "alpha-authored-report-status",
    "alpha-authored-state",
    "alpha-attest-status",
    "alpha-state-attested",
    "alpha-attested-object-id",
    "alpha-projection",
    "attest-human-status",
    "attest-human-code",
    "alpha-state-closed",
    "gamma-state-pending",
    "beta-first-state-ready",
  ],
  "P1B-E2": [
    ...fixtureProfileAssertionNames,
    ...journeyAssertionNames,
    "client1-list-status",
    "client2-list-status",
    "both-lists-equal",
    "race-one-success",
    "race-one-lease-held",
    "sibling-claim-refused",
    "objective-claim-refused",
    "beta-claim-status",
    "two-leases-live",
    ...harnessTaskAssertionNames("alpha-1"),
    ...harnessTaskAssertionNames("alpha-2"),
    ...harnessTaskAssertionNames("beta-1"),
    ...harnessTaskAssertionNames("beta-2"),
    "alpha-attest-status",
    "beta-attest-status",
    "alpha-state-attested",
    "beta-state-attested",
    "attested-object-ids-differ",
    "close-harness-forbidden",
    "alpha-closed",
    "gamma-pending-after-first-close",
    "beta-closed",
    "gamma-ready-after-second-close",
    "gamma-first-task-ready",
    "event-list-claims",
    "event-list-reports",
    "event-actor-ids-differ",
    "idempotency-first-status",
    "idempotency-second-status",
    "idempotency-bodies-differ",
    ...transportAssertionNames,
    ...disclosureAssertionNames,
  ],
  "P1B-E3": [
    ...fixtureProfileAssertionNames,
    ...journeyAssertionNames,
    "first-claim-status",
    "first-fence",
    "poll-refused-before-expiry",
    "takeover-status",
    "takeover-fence-greater",
    "state-before-stale-report",
    "stale-report-status",
    "state-after-stale-report",
    "takeover-report-status",
    "final-state-done",
    "outcome-events-count",
    "outcome-event-actor",
    ...disclosureAssertionNames,
  ],
};
