import { z } from "zod";
import {
  CREATE_MAX_BODY_BYTES,
  CREDENTIAL_TIMEOUT_MS,
  credentialAnswerSchema,
  credentialCreateSchema,
  credentialListAnswerSchema,
  credentialListQuerySchema,
  credentialParamsSchema,
  credentialPlatformListAnswerSchema,
  credentialRevisionParamsSchema,
  credentialRotateBodySchema,
  credentialUpdateMetadataBodySchema,
  METADATA_MAX_BODY_BYTES,
} from "../custody/contract.ts";
import { HttpMethod, HttpStatus } from "../kernel/http.ts";
import {
  AccessPolicy,
  OperationLifetime,
  StoreName,
  type Operation,
} from "../kernel/operation.ts";

export const REPOSITORY_COMPONENT_NAME = "repository";

const emptyParams = z.strictObject({});
const emptyQuery = z.strictObject({});

export const repositoryCredentialAnswerSchema = credentialAnswerSchema.extend({
  bindings: z.array(
    z.strictObject({
      projectId: z.string(),
      projectName: z.string(),
      bindingId: z.string(),
      name: z.string(),
    }),
  ),
});
export type RepositoryCredentialAnswer = z.infer<
  typeof repositoryCredentialAnswerSchema
>;

export const repositoryOperations = {
  platform_list: {
    id: "repository.credential.platform_list",
    service: REPOSITORY_COMPONENT_NAME,
    method: HttpMethod.Get,
    path: "/api/repository/credential/platform",
    access: AccessPolicy.Human,
    store: StoreName.Operational,
    lifetime: OperationLifetime.Unary,
    timeoutMs: CREDENTIAL_TIMEOUT_MS,
    mutation: false,
    body: false,
    status: HttpStatus.OK,
    input: z.strictObject({
      params: emptyParams,
      query: emptyQuery,
      body: z.null(),
    }),
    output: credentialPlatformListAnswerSchema,
    description: "List the repository credential platforms.",
  },
  create: {
    id: "repository.credential.create",
    service: REPOSITORY_COMPONENT_NAME,
    method: HttpMethod.Post,
    path: "/api/repository/credential",
    access: AccessPolicy.Human,
    store: StoreName.Operational,
    lifetime: OperationLifetime.Unary,
    timeoutMs: CREDENTIAL_TIMEOUT_MS,
    mutation: true,
    body: true,
    maxBodyBytes: CREATE_MAX_BODY_BYTES,
    status: HttpStatus.OK,
    input: z.strictObject({
      params: emptyParams,
      query: emptyQuery,
      body: credentialCreateSchema,
    }),
    output: credentialAnswerSchema,
    description: "Create a repository credential with its first revision.",
  },
  list: {
    id: "repository.credential.list",
    service: REPOSITORY_COMPONENT_NAME,
    method: HttpMethod.Get,
    path: "/api/repository/credential",
    access: AccessPolicy.Human,
    store: StoreName.Operational,
    lifetime: OperationLifetime.Unary,
    timeoutMs: CREDENTIAL_TIMEOUT_MS,
    mutation: false,
    body: false,
    status: HttpStatus.OK,
    input: z.strictObject({
      params: emptyParams,
      query: credentialListQuerySchema,
      body: z.null(),
    }),
    output: credentialListAnswerSchema,
    description:
      "List repository credentials with optional platform filtering and pagination.",
  },
  get: {
    id: "repository.credential.get",
    service: REPOSITORY_COMPONENT_NAME,
    method: HttpMethod.Get,
    path: "/api/repository/credential/:credentialName",
    access: AccessPolicy.Human,
    store: StoreName.Operational,
    lifetime: OperationLifetime.Unary,
    timeoutMs: CREDENTIAL_TIMEOUT_MS,
    mutation: false,
    body: false,
    status: HttpStatus.OK,
    input: z.strictObject({
      params: credentialParamsSchema,
      query: emptyQuery,
      body: z.null(),
    }),
    output: repositoryCredentialAnswerSchema,
    description:
      "Get a repository credential, all its revisions and the bindings that name it.",
  },
  rotate: {
    id: "repository.credential.rotate",
    service: REPOSITORY_COMPONENT_NAME,
    method: HttpMethod.Post,
    path: "/api/repository/credential/:credentialName/revision",
    access: AccessPolicy.Human,
    store: StoreName.Operational,
    lifetime: OperationLifetime.Unary,
    timeoutMs: CREDENTIAL_TIMEOUT_MS,
    mutation: true,
    body: true,
    maxBodyBytes: CREATE_MAX_BODY_BYTES,
    status: HttpStatus.OK,
    input: z.strictObject({
      params: credentialParamsSchema,
      query: emptyQuery,
      body: credentialRotateBodySchema,
    }),
    output: credentialAnswerSchema,
    description: "Rotate a repository credential secret into a new revision.",
  },
  update_metadata: {
    id: "repository.credential.update_metadata",
    service: REPOSITORY_COMPONENT_NAME,
    method: HttpMethod.Put,
    path: "/api/repository/credential/:credentialName/metadata",
    access: AccessPolicy.Human,
    store: StoreName.Operational,
    lifetime: OperationLifetime.Unary,
    timeoutMs: CREDENTIAL_TIMEOUT_MS,
    mutation: true,
    body: true,
    maxBodyBytes: METADATA_MAX_BODY_BYTES,
    status: HttpStatus.OK,
    input: z.strictObject({
      params: credentialParamsSchema,
      query: emptyQuery,
      body: credentialUpdateMetadataBodySchema,
    }),
    output: credentialAnswerSchema,
    description: "Update repository credential metadata in a new revision.",
  },
  revoke: {
    id: "repository.credential.revoke",
    service: REPOSITORY_COMPONENT_NAME,
    method: HttpMethod.Post,
    path: "/api/repository/credential/:credentialName/revision/:revision/revoke",
    access: AccessPolicy.Human,
    store: StoreName.Operational,
    lifetime: OperationLifetime.Unary,
    timeoutMs: CREDENTIAL_TIMEOUT_MS,
    mutation: true,
    body: false,
    status: HttpStatus.OK,
    input: z.strictObject({
      params: credentialRevisionParamsSchema,
      query: emptyQuery,
      body: z.null(),
    }),
    output: credentialAnswerSchema,
    description: "End an older repository credential revision.",
  },
  archive: {
    id: "repository.credential.archive",
    service: REPOSITORY_COMPONENT_NAME,
    method: HttpMethod.Post,
    path: "/api/repository/credential/:credentialName/archive",
    access: AccessPolicy.Human,
    store: StoreName.Operational,
    lifetime: OperationLifetime.Unary,
    timeoutMs: CREDENTIAL_TIMEOUT_MS,
    mutation: true,
    body: false,
    status: HttpStatus.OK,
    input: z.strictObject({
      params: credentialParamsSchema,
      query: emptyQuery,
      body: z.null(),
    }),
    output: credentialAnswerSchema,
    description: "Archive a repository credential that no dependent names.",
  },
} as const satisfies Record<string, Operation>;
