import { action, parameter, resource, sub } from "./path.ts";
import { operations } from "./operation.ts";

export const instruction = operations([
  {
    operationId: "agent.list",
    method: "GET",
    path: [resource("agent")],
    introducedIn: "phase-2",
    status: "stubbed",
    allowedActors: ["human"],
  },
  {
    operationId: "template.list",
    method: "GET",
    path: [resource("template")],
    introducedIn: "phase-2",
    status: "stubbed",
    allowedActors: ["human"],
  },
  {
    operationId: "template.show",
    method: "GET",
    path: [resource("template"), parameter("deferred")],
    introducedIn: "phase-2",
    status: "stubbed",
    allowedActors: ["human"],
  },
  {
    operationId: "profile.instantiate",
    method: "POST",
    path: [resource("repository"), parameter("repository"), sub("profile")],
    introducedIn: "phase-2",
    status: "stubbed",
    allowedActors: ["human"],
    idempotency: "memory",
    replayable: [200],
  },
  {
    operationId: "profile.export",
    method: "GET",
    path: [resource("repository"), parameter("repository"), sub("profile")],
    introducedIn: "phase-2",
    status: "stubbed",
    allowedActors: ["human"],
  },
  {
    operationId: "profile.import",
    method: "PUT",
    path: [resource("repository"), parameter("repository"), sub("profile")],
    introducedIn: "phase-2",
    status: "stubbed",
    allowedActors: ["human"],
  },
  {
    operationId: "profile.verify",
    method: "POST",
    path: [
      resource("repository"),
      parameter("repository"),
      sub("profile"),
      action("verify"),
    ],
    introducedIn: "phase-2",
    status: "stubbed",
    allowedActors: ["human"],
    idempotency: "memory",
    replayable: [200],
  },
  {
    operationId: "instructions.resolve",
    method: "GET",
    path: [resource("instruction"), action("resolve")],
    introducedIn: "phase-2",
    status: "stubbed",
    allowedActors: ["human"],
  },
]);
