"""Real compiled CLI/API acceptance, with disposable state and secret-free proof."""

import base64
import hashlib
import hmac
import http.client
import json
import os
from pathlib import Path
import pty
import re
import secrets
import select
import shutil
import signal
import socket
import subprocess
import tempfile
import time
from datetime import datetime, timezone

ENGINE = Path(__file__).resolve().parents[1]
ROOT = ENGINE.parent
NODE = shutil.which("node")
INQUIRY = "setup end-to-end test and then command and api to verify"
CRITERION = (
    "add the verification command and API; test JWTs generated by the real CLI "
    "for the default and an explicit username against a real compiled server; "
    "assert HTTP 200 and the matching human identity for valid tokens, HTTP 401 "
    "and CLI failure for missing, tampered, expired or wrong-key tokens; record "
    "sanitized CLI/API evidence and clean up the isolated environment."
)
TOKEN = rb"([A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+)\r?\n"


def require(condition, message):
    if not condition:
        raise AssertionError(message)


def git(directory, *args):
    return subprocess.check_output(["git", *args], cwd=directory, text=True).strip()


def terminal_read(master, process, pattern):
    data = b""
    deadline = time.monotonic() + 15
    while time.monotonic() < deadline:
        if select.select([master], [], [], 0.1)[0]:
            try:
                data += os.read(master, 65536)
            except OSError:
                break
            match = re.search(pattern, data)
            if match:
                return match.group(1).decode()
        if process.poll() is not None:
            break
    raise AssertionError("Terminal did not produce the expected JWT")


def decode_part(part):
    return base64.urlsafe_b64decode(part + "=" * (-len(part) % 4))


class Run:
    def __init__(self):
        os.umask(0o077)
        date = datetime.now(timezone.utc).strftime("%y%m%d")
        parent = ROOT / ".dev/e2e"
        parent.mkdir(parents=True, exist_ok=True)
        name = date + "-jwt-verification"
        self.path = parent / name
        suffix = 2
        while self.path.exists():
            self.path = parent / f"{name}-{suffix}"
            suffix += 1
        self.path.mkdir()
        (self.path / "steps").mkdir()
        temp = Path(tempfile.gettempdir()) / "opencode"
        temp.mkdir(mode=0o700, exist_ok=True)
        self.home = Path(tempfile.mkdtemp(prefix="kanthord-jwt-e2e-", dir=temp))
        self.env = dict(os.environ)
        for key in list(self.env):
            if key.startswith("KANTHORD_"):
                del self.env[key]
        self.env.update({f"XDG_{kind}_HOME": str(self.home / kind.lower()) for kind in ["CONFIG", "DATA", "STATE", "CACHE"]})
        self.env["KANTHORD_CONFIG"] = str(self.home / "config/kanthord/kanthord.yaml")
        self.env["HOME"] = str(self.home)
        self.tag = f"e2e-{date}-{secrets.token_hex(4)}"
        self.sentinel = secrets.token_urlsafe(32)
        self.secrets = [self.sentinel]
        self.daemon = None
        self.server_output = None
        self.console = None
        self.failure = None
        self.metadata = {
            "startedAt": datetime.now(timezone.utc).isoformat(),
            "inquiry": INQUIRY, "criterionVerbatim": CRITERION,
            "criteriaSource": "User approved CLI/API proof in this conversation",
            "candidateObjectives": [], "taskFiles": [],
            "engineCommit": git(ENGINE, "rev-parse", "HEAD"),
            "engineDirty": git(ENGINE, "status", "--porcelain"),
            "appsCommit": git(ROOT / "apps", "rev-parse", "HEAD"),
            "appsDirty": git(ROOT / "apps", "status", "--porcelain"),
            "mode": "Local CLI/API acceptance; browser screenshots explicitly waived",
            "startedOrReused": "Start a fresh compiled engine; no reused process",
            "recordTag": self.tag, "home": str(self.home), "steps": [],
            "createdRecords": "Disposable server configuration and operational schema; no saved CLI token, human account or worker registration",
            "legacyEngineLogOffset": (ROOT / ".dev/engine.log").stat().st_size if (ROOT / ".dev/engine.log").exists() else 0,
            "log": "console.log", "logOffset": 0,
            "observables": [
                "Step 01: config init exit 0, private file, compiled-binary hashes and fresh PID prove isolated setup.",
                "Step 02: health HTTP 200 with redirected, empty stdout proves startup without token issuance.",
                "Step 03: real CLI JWTs decode to the default and exact per-run username and verify under the configured key.",
                "Step 04: each valid token produces HTTP 200 and CLI exit 0 with its matching identity.",
                "Step 05: missing, tampered, expired, wrong-key and malformed tokens produce HTTP 401 and CLI exit 1.",
                "Step 06: an environment token allows verify without login; removed commands fail; OpenAPI publishes human verification and worker registration.",
                "Step 07: SIGTERM exit 0, removed home and closed port prove cleanup.",
                "Step 08: scan every evidence file for the sentinel, all JWTs and master keys.",
            ],
        }
        self.save()

    def save(self):
        (self.path / "run.json").write_text(json.dumps(self.metadata, indent=2) + "\n")

    def step(self, name, observation):
        number = len(self.metadata["steps"]) + 1
        artifact = f"steps/{number:02}-{name}.json"
        (self.path / artifact).write_text(json.dumps(observation, indent=2) + "\n")
        self.metadata["steps"].append({"name": name, "artifact": artifact, "passed": True})
        self.save()
        print(f"PASS {number:02} {name}", flush=True)

    def command(self, args):
        return subprocess.run([NODE, "bin/kanthord.mjs", *args], cwd=ENGINE, env=self.env,
                              stdin=subprocess.DEVNULL, capture_output=True, text=True, timeout=20)

    def helper(self, source):
        result = subprocess.run([NODE, "--input-type=module", "-e", source], cwd=ENGINE,
                                env=self.env, capture_output=True, text=True, timeout=15)
        require(result.returncode == 0, "Configuration preparation failed")
        return json.loads(result.stdout)

    def jwt(self, *args):
        master, slave = pty.openpty()
        child = subprocess.Popen([NODE, "bin/kanthord.mjs", "jwt", *args],
                                 cwd=ENGINE, env=self.env, stdin=subprocess.DEVNULL,
                                 stdout=slave, stderr=subprocess.PIPE)
        os.close(slave)
        try:
            token = terminal_read(master, child, rb"^" + TOKEN)
            self.secrets.append(token)
            require(child.wait(timeout=10) == 0, "JWT command failed")
            return token
        finally:
            if child.poll() is None:
                child.kill()
                child.wait()
            child.stderr.close()
            os.close(master)

    def inspect(self, token, master_key, username):
        header, payload, signature = token.split(".")
        # Independently verify HKDF-SHA256 and HS256 with Python's standard library.
        prk = hmac.new(b"\0" * 32, base64.b64decode(master_key), hashlib.sha256).digest()
        key = hmac.new(prk, b"gateway/jwt-hs256/v1\x01", hashlib.sha256).digest()
        expected = hmac.new(key, f"{header}.{payload}".encode(), hashlib.sha256).digest()
        require(hmac.compare_digest(expected, decode_part(signature)), "JWT signature verification failed")
        decoded = {"header": json.loads(decode_part(header)), "payload": json.loads(decode_part(payload))}
        require(decoded["header"] == {"alg": "HS256", "typ": "JWT"}, "Unexpected JWT header")
        require(decoded["payload"]["sub"] == username and decoded["payload"]["kind"] == "human", "Unexpected JWT identity")
        require(set(decoded["payload"]) == {"sub", "name", "kind", "iat", "exp", "jti"}, "Unexpected JWT fields")
        require(decoded["payload"]["name"] == username, "Unexpected JWT display name")
        require(decoded["payload"]["exp"] > time.time(), "JWT is expired")
        return decoded

    def request(self, path, token=None):
        connection = http.client.HTTPConnection("127.0.0.1", self.metadata["port"], timeout=5)
        try:
            headers = {} if token is None else {"Authorization": f"Bearer {token}"}
            connection.request("GET", path, headers=headers)
            response = connection.getresponse()
            body = response.read().decode()
            with (self.path / "requests.jsonl").open("a") as output:
                output.write(json.dumps({"method": "GET", "path": path, "status": response.status}) + "\n")
            return response.status, body
        finally:
            connection.close()

    def verify(self, token):
        args = ["gateway", "verify", "--endpoint", self.metadata["endpoint"]]
        if token is not None:
            args += ["--token", token]
        return self.command(args)

    def exercise(self):
        require(NODE is not None, "Node.js is required")
        initialized = self.command(["config", "init"])
        require(initialized.returncode == 0, "config init failed")
        with socket.socket() as listener:
            listener.bind(("127.0.0.1", 0))
            port = listener.getsockname()[1]
        self.env["E2E_PORT"] = str(port)
        prepared = self.helper("""
          import { loadConfig } from './dist/config/index.js';
          import { writePrivate } from './dist/kernel/files.js';
          import { randomBytes } from 'node:crypto';
          import { stringify } from 'yaml';
          const file = process.env.KANTHORD_CONFIG;
          const config = loadConfig(file);
          config.gateway.port = Number(process.env.E2E_PORT);
          config.gateway.allowedHosts = [`127.0.0.1:${config.gateway.port}`];
          config.gateway.tokenLifetime = 600;
          writePrivate(file, stringify(config), true);
          writePrivate(file + '.expired', stringify({...config, gateway: {...config.gateway, tokenLifetime: 0}}));
          const other = {...config, masterKey: randomBytes(32).toString('base64')};
          writePrivate(file + '.wrong-key', stringify(other));
          console.log(JSON.stringify({masterKey: config.masterKey, otherKey: other.masterKey}));
        """)
        self.secrets.extend(prepared.values())
        self.metadata.update({"port": port, "endpoint": f"http://127.0.0.1:{port}"})
        hashes = {str(path.relative_to(ENGINE)): hashlib.sha256(path.read_bytes()).hexdigest()
                  for path in sorted((ENGINE / "dist").rglob("*.js"))}
        self.metadata["compiledSHA256"] = hashes
        self.step("isolated-configuration", {"command": "kanthord config init", "exitCode": 0,
                   "configMode": oct(Path(self.env["KANTHORD_CONFIG"]).stat().st_mode & 0o777), "lifetimeSeconds": 600})
        self.console = (self.path / "console.log").open("wb")
        self.server_output = (self.home / "server.stdout").open("w+b")
        self.daemon = subprocess.Popen([NODE, "bin/kanthord.mjs", "serve"], cwd=ENGINE,
                                       env=self.env, stdin=subprocess.DEVNULL, stdout=self.server_output, stderr=self.console)
        self.metadata["pid"] = self.daemon.pid
        self.save()
        self.wait_ready()
        self.server_output.seek(0)
        require(self.server_output.read() == b"", "Server startup printed unexpected output")
        self.step("server-ready", {"healthStatus": 200, "stdoutRedirected": True, "stdoutEmpty": True})
        default = self.jwt()
        custom = self.jwt(self.tag)
        self.step("cli-generation", {
            "default": self.inspect(default, prepared["masterKey"], "kanthorlabs"),
            "explicit": self.inspect(custom, prepared["masterKey"], self.tag),
            "commands": ["kanthord jwt", f"kanthord jwt {self.tag}"],
        })
        observations = []
        for name, token, username in [("default", default, "kanthorlabs"), ("explicit", custom, self.tag)]:
            status, body = self.request("/api/auth/verify", token)
            expected = {"kind": "human", "sub": username, "name": username}
            require(status == 200 and json.loads(body) == expected, "Valid token API verification failed")
            cli = self.verify(token)
            require(cli.returncode == 0 and json.loads(cli.stdout) == expected, "Valid token CLI verification failed")
            require(not cli.stderr, "Successful CLI verification emitted a diagnostic")
            observations.append({"case": name, "status": status, "exitCode": cli.returncode, "identity": expected})
        self.step("valid-verification", {"cases": observations})
        header, payload, signature = custom.split(".")
        tampered = f"{header}.{payload}.{'A' if signature[0] != 'A' else 'B'}{signature[1:]}"
        invalid = {
            "missing": None, "tampered": tampered,
            "expired": self.jwt("--config", self.env["KANTHORD_CONFIG"] + ".expired"),
            "wrong-key": self.jwt("--config", self.env["KANTHORD_CONFIG"] + ".wrong-key"),
            "malformed": self.sentinel,
            "machine": self.jwt("--binding", "e2e-worker-binding", "--name", "E2E worker"),
        }
        self.secrets.extend(value for value in invalid.values() if value)
        rejected = []
        for name, token in invalid.items():
            status, body = self.request("/api/auth/verify", token)
            require(status == 401 and json.loads(body)["error"]["code"] == "gateway.authentication.unauthorized", "Invalid token API verification was not rejected")
            cli = self.verify(token)
            require(cli.returncode == 1 and not cli.stdout and "HTTP 401" in cli.stderr and cli.stderr.startswith("gateway.authentication.unauthorized:"), "Invalid token CLI verification was not rejected")
            require(not any(value in cli.stderr for value in self.secrets), "CLI diagnostic disclosed a credential")
            rejected.append({"case": name, "status": status, "exitCode": cli.returncode, "code": "gateway.authentication.unauthorized"})
        self.step("invalid-verification", {"cases": rejected})
        self.env["KANTHORD_TOKEN"] = custom
        try:
            resolved = self.verify(None)
        finally:
            del self.env["KANTHORD_TOKEN"]
        require(resolved.returncode == 0 and json.loads(resolved.stdout) == {"kind": "human", "sub": self.tag, "name": self.tag}, "Environment token verification failed")
        for name in ["jwt", "login", "logout"]:
            removed = self.command(["gateway", name])
            require(removed.returncode == 1 and not removed.stdout, "Removed gateway command remains available")
        require(not (self.home / "config/kanthord/cli.yaml").exists(), "CLI unexpectedly saved credentials")
        status, contract = self.request("/api/openapi/gateway/verify.yaml")
        require(status == 200 and "gateway.verify" in contract and "x-access-policy: human" in contract and "bearerAuth:" in contract, "Published verification contract missing")
        require("sub:" in contract and "name:" in contract and "accountId" not in contract, "Published verification contract must preserve JWT property names")
        worker_status, worker_contract = self.request("/api/openapi/worker/register.yaml")
        require(worker_status == 200 and "worker.register" in worker_contract, "Published worker registration contract missing")
        root_status, root_contract = self.request("/api/openapi.yaml")
        require(root_status == 200 and "/api/worker/register:" in root_contract and "/api/auth/register:" not in root_contract, "Registration path is incorrect")
        self.step("environment-token-and-contract", {"environmentTokenCLIExitCode": resolved.returncode, "identity": json.loads(resolved.stdout), "openapiStatus": status, "workerContractStatus": worker_status, "removedCommandsRejected": True, "savedClientFile": False})

    def wait_ready(self):
        require(self.daemon is not None, "Server process is required")
        deadline = time.monotonic() + 10
        for attempt in range(200):
            require(self.daemon.poll() is None, "Server exited before readiness")
            # A refused connection is expected only while this fresh listener binds.
            try:
                status, body = self.request("/api/healthcheck")
            except ConnectionRefusedError:
                status, body = None, None
            if status == 200:
                require(json.loads(body)["status"] == "ok", "Health response failed")
                return
            require(time.monotonic() < deadline, "Server did not become ready")
            time.sleep(0.05)
        raise AssertionError("Server did not become ready within the attempt limit")

    def cleanup(self):
        forced = False
        if self.daemon and self.daemon.poll() is None:
            self.daemon.send_signal(signal.SIGTERM)
            try:
                self.daemon.wait(timeout=12)
            except subprocess.TimeoutExpired:
                forced = True
                self.daemon.kill()
                self.daemon.wait()
        stdout_empty = True
        if self.server_output:
            self.server_output.seek(0)
            stdout_empty = self.server_output.read() == b""
            self.server_output.close()
        if self.console:
            self.console.close()
        shutil.rmtree(self.home)
        released = True
        if "port" in self.metadata:
            with socket.socket() as probe:
                probe.settimeout(1)
                released = probe.connect_ex(("127.0.0.1", self.metadata["port"])) != 0
        cleanup = {"engineStopped": not self.daemon or self.daemon.poll() is not None,
                   "exitCode": self.daemon.returncode if self.daemon else None,
                   "forced": forced, "homeRemoved": not self.home.exists(), "portReleased": released, "stdoutEmpty": stdout_empty}
        self.metadata["cleanup"] = cleanup
        self.save()
        require(not forced and (not self.daemon or self.daemon.returncode == 0) and cleanup["homeRemoved"] and released and stdout_empty, "Graceful cleanup failed or server printed unexpected output")
        self.step("cleanup", cleanup)

    def report(self):
        steps = {step["name"]: step for step in self.metadata["steps"]}
        criteria = [
            ("isolated-configuration", "Use disposable configuration/data and the compiled launcher", "Process evidence"),
            ("server-ready", "Start a real server with redirected stdout and no token issuance", "Process evidence and empty-output assertion"),
            ("cli-generation", "Generate default and explicit-username JWTs with the real CLI", "Command evidence and decoded-claim assertions"),
            ("valid-verification", "Valid JWTs return HTTP 200 and CLI success with the matching human identity", "Network metadata and identity assertions"),
            ("invalid-verification", "Missing, tampered, expired and wrong-key tokens return HTTP 401 and CLI failure", "Network metadata and exit-code assertions"),
            ("environment-token-and-contract", "Verify using an environment token without login and publish human verification and worker registration contracts", "Command evidence and contract assertion"),
            ("cleanup", "Stop the isolated server and remove its disposable state", "Process evidence"),
            ("secrecy", "Keep credentials out of all saved evidence", "Sentinel sweep"),
        ]
        lines = ["# JWT verification acceptance", "", "## Run record", "",
                 f"- User inquiry: {INQUIRY}", f"- Started: {self.metadata['startedAt']}",
                 "- Criteria source: user-approved CLI/API proof; no matching objective or task files.",
                 f"- Engine: `{self.metadata['engineCommit']}`; dirty state recorded in `run.json`.",
                 f"- Apps: `{self.metadata['appsCommit']}`; dirty state recorded; no app process used.",
                 f"- Fresh compiled engine PID: `{self.metadata.get('pid')}`; endpoint: `{self.metadata.get('endpoint')}`.",
                 f"- Disposable home: `{self.home}`. Compiled-file SHA-256 hashes are in `run.json`.",
                 "- Local CLI/API acceptance with real PTYs for token output. Browser screenshots were explicitly waived.",
                 "- Server log: `console.log` from byte zero. Existing `.dev/engine.log` offset is recorded but that log is not used.",
                 "", "## Checklist", "", f"> {CRITERION}", ""]
        for name, text, evidence in criteria:
            step = steps.get(name)
            lines.append(f"- [{'x' if step else ' '}] {text} — evidence: {evidence} — proof: `{step['artifact'] if step else 'not reached'}` — observed: {'PASS' if step else 'not proven'}.")
        lines += ["", "## Steps", "", "| Step | Action | Proof | Result |", "|---|---|---|---|"]
        for number, step in enumerate(self.metadata["steps"], 1):
            lines.append(f"| {number} | {step['name']} | `{step['artifact']}` | PASS |")
        lines += ["", "## Defects", "", self.failure or "None observed.", "", "## Verdict", "", self.metadata["verdict"], ""]
        (self.path / "report.md").write_text("\n".join(lines))

    def finish(self):
        try:
            self.exercise()
        except Exception as error:
            self.failure = str(error) if isinstance(error, AssertionError) else type(error).__name__
        finally:
            try:
                self.cleanup()
            except Exception:
                self.failure = self.failure or "Cleanup failed"
        self.metadata["finishedAt"] = datetime.now(timezone.utc).isoformat()
        self.metadata["verdict"] = "FAIL" if self.failure else "PASS"
        self.metadata["failure"] = self.failure
        self.save()
        self.report()
        leaked = []
        for path in self.path.rglob("*"):
            if path.is_file():
                content = path.read_text()
                if any(value in content for value in self.secrets):
                    # Preserve a safe failure artifact instead of retaining a secret.
                    for value in self.secrets:
                        content = content.replace(value, "[Redacted]")
                    path.write_text(content)
                    leaked.append(str(path.relative_to(self.path)))
        if leaked:
            self.failure = "Credential sweep failed; affected artifacts were redacted"
            self.metadata.update({"verdict": "FAIL", "failure": self.failure, "redactedArtifacts": leaked})
        else:
            self.step("secrecy", {"sentinelSweepPassed": True, "rawTokensRecorded": False, "masterKeysRecorded": False})
        self.save()
        self.report()
        print(json.dumps({"verdict": self.metadata["verdict"], "report": str(self.path / "report.md"), "cleanup": self.metadata.get("cleanup")}))
        return 0 if self.metadata["verdict"] == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(Run().finish())
