import { z } from "zod";
import {
  CREATE_MAX_BODY_BYTES,
  CREDENTIAL_TIMEOUT_MS,
  credentialAnswerSchema,
  credentialCheckAnswerSchema,
  credentialCheckBodySchema,
  credentialCreateSchema,
  credentialListAnswerSchema,
  credentialListQuerySchema,
  credentialParamsSchema,
  credentialPlatformListAnswerSchema,
  credentialRevisionParamsSchema,
  credentialRotateBodySchema,
  credentialUpdateMetadataBodySchema,
  METADATA_MAX_BODY_BYTES,
} from "../custody/contract.ts";
import { HttpMethod, HttpStatus } from "../kernel/http.ts";
import {
  AccessPolicy,
  OperationLifetime,
  StoreName,
  type Operation,
} from "../kernel/operation.ts";

export const STORAGE_COMPONENT_NAME = "storage";

const emptyParams = z.strictObject({});
const emptyQuery = z.strictObject({});

export const storageCredentialAnswerSchema = credentialAnswerSchema.extend({
  bindings: z.array(
    z.strictObject({
      projectId: z.string(),
      projectName: z.string(),
      bindingId: z.string(),
      name: z.string(),
    }),
  ),
});
export type StorageCredentialAnswer = z.infer<
  typeof storageCredentialAnswerSchema
>;

export const storageOperations = {
  platform_list: {
    id: "storage.credential.platform_list",
    service: STORAGE_COMPONENT_NAME,
    method: HttpMethod.Get,
    path: "/api/storage/credential/platform",
    access: AccessPolicy.Human,
    store: StoreName.Operational,
    lifetime: OperationLifetime.Unary,
    timeoutMs: CREDENTIAL_TIMEOUT_MS,
    mutation: false,
    body: false,
    status: HttpStatus.OK,
    input: z.strictObject({
      params: emptyParams,
      query: emptyQuery,
      body: z.null(),
    }),
    output: credentialPlatformListAnswerSchema,
    description: "List the storage credential platforms.",
  },
  create: {
    id: "storage.credential.create",
    service: STORAGE_COMPONENT_NAME,
    method: HttpMethod.Post,
    path: "/api/storage/credential",
    access: AccessPolicy.Human,
    store: StoreName.Operational,
    lifetime: OperationLifetime.Unary,
    timeoutMs: CREDENTIAL_TIMEOUT_MS,
    mutation: true,
    body: true,
    maxBodyBytes: CREATE_MAX_BODY_BYTES,
    status: HttpStatus.OK,
    input: z.strictObject({
      params: emptyParams,
      query: emptyQuery,
      body: credentialCreateSchema,
    }),
    output: credentialAnswerSchema,
    description: "Create a storage credential with its first revision.",
  },
  list: {
    id: "storage.credential.list",
    service: STORAGE_COMPONENT_NAME,
    method: HttpMethod.Get,
    path: "/api/storage/credential",
    access: AccessPolicy.Human,
    store: StoreName.Operational,
    lifetime: OperationLifetime.Unary,
    timeoutMs: CREDENTIAL_TIMEOUT_MS,
    mutation: false,
    body: false,
    status: HttpStatus.OK,
    input: z.strictObject({
      params: emptyParams,
      query: credentialListQuerySchema,
      body: z.null(),
    }),
    output: credentialListAnswerSchema,
    description:
      "List storage credentials with optional platform filtering and pagination.",
  },
  get: {
    id: "storage.credential.get",
    service: STORAGE_COMPONENT_NAME,
    method: HttpMethod.Get,
    path: "/api/storage/credential/:credential_name",
    access: AccessPolicy.Human,
    store: StoreName.Operational,
    lifetime: OperationLifetime.Unary,
    timeoutMs: CREDENTIAL_TIMEOUT_MS,
    mutation: false,
    body: false,
    status: HttpStatus.OK,
    input: z.strictObject({
      params: credentialParamsSchema,
      query: emptyQuery,
      body: z.null(),
    }),
    output: storageCredentialAnswerSchema,
    description:
      "Get a storage credential, all its revisions and the bindings that name it.",
  },
  rotate: {
    id: "storage.credential.rotate",
    service: STORAGE_COMPONENT_NAME,
    method: HttpMethod.Post,
    path: "/api/storage/credential/:credential_name/revision",
    access: AccessPolicy.Human,
    store: StoreName.Operational,
    lifetime: OperationLifetime.Unary,
    timeoutMs: CREDENTIAL_TIMEOUT_MS,
    mutation: true,
    body: true,
    maxBodyBytes: CREATE_MAX_BODY_BYTES,
    status: HttpStatus.OK,
    input: z.strictObject({
      params: credentialParamsSchema,
      query: emptyQuery,
      body: credentialRotateBodySchema,
    }),
    output: credentialAnswerSchema,
    description: "Rotate a storage credential secret into a new revision.",
  },
  update_metadata: {
    id: "storage.credential.update_metadata",
    service: STORAGE_COMPONENT_NAME,
    method: HttpMethod.Put,
    path: "/api/storage/credential/:credential_name/metadata",
    access: AccessPolicy.Human,
    store: StoreName.Operational,
    lifetime: OperationLifetime.Unary,
    timeoutMs: CREDENTIAL_TIMEOUT_MS,
    mutation: true,
    body: true,
    maxBodyBytes: METADATA_MAX_BODY_BYTES,
    status: HttpStatus.OK,
    input: z.strictObject({
      params: credentialParamsSchema,
      query: emptyQuery,
      body: credentialUpdateMetadataBodySchema,
    }),
    output: credentialAnswerSchema,
    description: "Update storage credential metadata in a new revision.",
  },
  revoke: {
    id: "storage.credential.revoke",
    service: STORAGE_COMPONENT_NAME,
    method: HttpMethod.Post,
    path: "/api/storage/credential/:credential_name/revision/:revision/revoke",
    access: AccessPolicy.Human,
    store: StoreName.Operational,
    lifetime: OperationLifetime.Unary,
    timeoutMs: CREDENTIAL_TIMEOUT_MS,
    mutation: true,
    body: false,
    status: HttpStatus.OK,
    input: z.strictObject({
      params: credentialRevisionParamsSchema,
      query: emptyQuery,
      body: z.null(),
    }),
    output: credentialAnswerSchema,
    description: "End an older storage credential revision.",
  },
  archive: {
    id: "storage.credential.archive",
    service: STORAGE_COMPONENT_NAME,
    method: HttpMethod.Post,
    path: "/api/storage/credential/:credential_name/archive",
    access: AccessPolicy.Human,
    store: StoreName.Operational,
    lifetime: OperationLifetime.Unary,
    timeoutMs: CREDENTIAL_TIMEOUT_MS,
    mutation: true,
    body: false,
    status: HttpStatus.OK,
    input: z.strictObject({
      params: credentialParamsSchema,
      query: emptyQuery,
      body: z.null(),
    }),
    output: credentialAnswerSchema,
    description: "Archive a storage credential that no dependent names.",
  },
  check: {
    id: "storage.credential.check",
    service: STORAGE_COMPONENT_NAME,
    method: HttpMethod.Post,
    path: "/api/storage/credential/check",
    access: AccessPolicy.Human,
    store: StoreName.Operational,
    lifetime: OperationLifetime.Unary,
    timeoutMs: CREDENTIAL_TIMEOUT_MS,
    mutation: false,
    body: true,
    maxBodyBytes: CREATE_MAX_BODY_BYTES,
    status: HttpStatus.OK,
    input: z.strictObject({
      params: emptyParams,
      query: emptyQuery,
      body: credentialCheckBodySchema,
    }),
    output: credentialCheckAnswerSchema,
    description: "Check a typed storage credential secret before it is saved.",
  },
  verify: {
    id: "storage.credential.verify",
    service: STORAGE_COMPONENT_NAME,
    method: HttpMethod.Post,
    path: "/api/storage/credential/:credential_name/verify",
    access: AccessPolicy.Human,
    store: StoreName.Operational,
    lifetime: OperationLifetime.Unary,
    timeoutMs: CREDENTIAL_TIMEOUT_MS,
    mutation: false,
    body: false,
    status: HttpStatus.OK,
    input: z.strictObject({
      params: credentialParamsSchema,
      query: emptyQuery,
      body: z.null(),
    }),
    output: credentialCheckAnswerSchema,
    description: "Verify one stored storage credential record.",
  },
} as const satisfies Record<string, Operation>;
