import type { Migration } from "./migration.ts";

export const migration0007ExternalExecution: Migration = {
  version: 7,
  name: "0007-external-execution",
  rebuild: true,
  statements: [
    `ALTER TABLE run RENAME TO run_old`,
    `ALTER TABLE attempt RENAME TO attempt_old`,
    `ALTER TABLE lease RENAME TO lease_old`,
    `DROP INDEX run_one_active`,
    `CREATE TABLE run (
  id            TEXT PRIMARY KEY,
  kind          TEXT NOT NULL CHECK (kind IN ('objective', 'task')),
  node_id       TEXT NOT NULL REFERENCES node(id),
  parent_run_id TEXT REFERENCES run(id),
  driver        TEXT NOT NULL CHECK (driver IN ('internal', 'external')),
  workspace_id  TEXT REFERENCES workspace(id),
  worker        TEXT,
  lease_fence   INTEGER NOT NULL,
  attempt_limit INTEGER NOT NULL,
  base_oid      TEXT,
  head_oid      TEXT,
  state         TEXT NOT NULL CHECK (state IN ('active', 'ended')),
  outcome       TEXT,
  ended_at      INTEGER,
  CHECK ((kind = 'objective') = (parent_run_id IS NULL)),
  CHECK ((driver = 'internal') = (workspace_id IS NOT NULL)),
  CHECK ((driver = 'internal') = (worker IS NOT NULL)),
  CHECK ((driver = 'internal') = (base_oid IS NOT NULL)),
  UNIQUE (id, driver)
) STRICT`,
    `CREATE UNIQUE INDEX run_one_active ON run (node_id) WHERE state = 'active'`,
    `CREATE TABLE attempt (
  id             TEXT PRIMARY KEY,
  run_id         TEXT NOT NULL REFERENCES run(id),
  driver         TEXT NOT NULL CHECK (driver IN ('internal', 'external')),
  attempt_no     INTEGER NOT NULL,
  provider_id    TEXT REFERENCES provider(id),
  provider_model TEXT,
  timeout_ms     INTEGER,
  base_oid       TEXT,
  head_oid       TEXT,
  outcome        TEXT CHECK (outcome IS NULL OR outcome IN
                 ('accepted', 'rejected', 'failed', 'timed-out', 'cancelled')),
  ended_at       INTEGER,
  UNIQUE (run_id, attempt_no),
  CHECK ((driver = 'internal') = (provider_id IS NOT NULL)),
  CHECK ((driver = 'internal') = (provider_model IS NOT NULL)),
  CHECK ((driver = 'internal') = (timeout_ms IS NOT NULL)),
  CHECK ((driver = 'internal') = (base_oid IS NOT NULL)),
  FOREIGN KEY (run_id, driver) REFERENCES run(id, driver)
) STRICT`,
    `CREATE TABLE lease (
  subject_kind TEXT NOT NULL CHECK (subject_kind IN ('node', 'repository')),
  subject_id   TEXT NOT NULL,
  owner        TEXT,
  owner_kind   TEXT CHECK (owner_kind IS NULL OR owner_kind IN ('daemon', 'actor')),
  fence        INTEGER NOT NULL,
  acquired_at  INTEGER,
  renewed_at   INTEGER,
  expires_at   INTEGER,
  PRIMARY KEY (subject_kind, subject_id),
  CHECK ((owner IS NULL) = (owner_kind IS NULL)),
  CHECK (owner_kind <> 'actor' OR owner LIKE 'actor\\_%' ESCAPE '\\')
) STRICT`,
    `INSERT INTO run (id, kind, node_id, parent_run_id, driver, workspace_id, worker, lease_fence, attempt_limit, base_oid, head_oid, state, outcome, ended_at) SELECT id, kind, node_id, parent_run_id, 'internal', workspace_id, worker, lease_fence, attempt_limit, base_oid, head_oid, state, outcome, ended_at FROM run_old`,
    `INSERT INTO attempt (id, run_id, driver, attempt_no, provider_id, provider_model, timeout_ms, base_oid, head_oid, outcome, ended_at) SELECT id, run_id, 'internal', attempt_no, provider_id, provider_model, timeout_ms, base_oid, head_oid, outcome, ended_at FROM attempt_old`,
    `INSERT INTO lease (subject_kind, subject_id, owner, owner_kind, fence, acquired_at, renewed_at, expires_at) SELECT subject_kind, subject_id, owner, CASE WHEN owner IS NULL THEN NULL ELSE 'daemon' END, fence, acquired_at, renewed_at, expires_at FROM lease_old`,
    `DROP TABLE attempt_old`,
    `DROP TABLE run_old`,
    `DROP TABLE lease_old`,
  ],
};
