import type { Migration } from "./migration.ts";

export const migration0011Deliverable: Migration = {
  version: 11,
  name: "0011-deliverable",
  rebuild: true,
  statements: [
    "PRAGMA foreign_keys = OFF",
    `CREATE TABLE node_new (
  id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL REFERENCES project(id),
  kind TEXT NOT NULL CHECK (kind IN ('initiative', 'objective', 'task')),
  parent_id TEXT REFERENCES node(id),
  title TEXT NOT NULL,
  instruction_blob TEXT NOT NULL REFERENCES blob(hash),
  acceptance_blob TEXT REFERENCES blob(hash),
  worker TEXT,
  repository_id TEXT REFERENCES repository(id),
  state TEXT NOT NULL,
  block_reason TEXT,
  discard_reason TEXT,
  revision TEXT NOT NULL REFERENCES plan_revision(id),
  updated_at INTEGER NOT NULL,
  deliverable TEXT,
  verify_json TEXT,
  assignment TEXT,
  CHECK ((kind = 'initiative') = (parent_id IS NULL)),
  CHECK ((kind = 'objective') = (repository_id IS NOT NULL)),
  CHECK ((kind = 'task') = (acceptance_blob IS NOT NULL)),
  CHECK (state IN ('pending', 'ready', 'running', 'blocked',
                   'awaiting_approval', 'done', 'partial', 'discarded')),
  CHECK ((state = 'blocked') = (block_reason IS NOT NULL)),
  CHECK (block_reason IS NULL OR block_reason IN ('attempt-limit', 'dependency-discarded',
                   'stale-base', 'dirty-recovery', 'e2e-failed', 'abandoned')),
  CHECK (state <> 'awaiting_approval' OR kind = 'objective'),
  CHECK (state <> 'partial' OR kind <> 'task'),
  CHECK (deliverable IS NULL OR deliverable IN
        ('test', 'implementation', 'review', 'expansion')),
  CHECK (deliverable IS NULL OR kind <> 'initiative' OR deliverable = 'expansion'),
  CHECK (deliverable IS NULL OR kind <> 'task' OR deliverable <> 'expansion'),
  CHECK (verify_json IS NULL OR json_valid(verify_json))
) STRICT`,
    `INSERT INTO node_new SELECT id, project_id, kind, parent_id, title, instruction_blob, acceptance_blob, worker, repository_id, state, block_reason, discard_reason, revision, updated_at, NULL, NULL, NULL FROM node`,
    "DROP TABLE node",
    "ALTER TABLE node_new RENAME TO node",
    "CREATE INDEX node_project ON node (project_id, id)",
    "PRAGMA foreign_keys = ON",
  ],
};
