import type { Migration } from "./migration.ts";

export const executionAndJournal: Migration = {
  version: 3,
  name: "0003-execution-and-journal",
  statements: [
    `CREATE TABLE workspace (
  id                    TEXT PRIMARY KEY,
  node_id               TEXT NOT NULL UNIQUE REFERENCES node(id),
  repository_id         TEXT NOT NULL REFERENCES repository(id),
  path                  TEXT NOT NULL,
  clone_base_oid        TEXT NOT NULL,
  upstream_oid_at_clone TEXT NOT NULL,
  profile_blob          TEXT NOT NULL REFERENCES blob(hash),
  convention_version    TEXT NOT NULL,
  ambient_blob          TEXT REFERENCES blob(hash),
  state                 TEXT NOT NULL,
  updated_at            INTEGER NOT NULL
) STRICT`,
    `CREATE TABLE lease (
  subject_kind TEXT NOT NULL CHECK (subject_kind IN ('node', 'repository')),
  subject_id   TEXT NOT NULL,
  owner        TEXT,
  fence        INTEGER NOT NULL,
  acquired_at  INTEGER,
  renewed_at   INTEGER,
  expires_at   INTEGER,
  PRIMARY KEY (subject_kind, subject_id)
) STRICT`,
    `CREATE TABLE run (
  id            TEXT PRIMARY KEY,
  kind          TEXT NOT NULL CHECK (kind IN ('objective', 'task')),
  node_id       TEXT NOT NULL REFERENCES node(id),
  parent_run_id TEXT REFERENCES run(id),
  workspace_id  TEXT NOT NULL REFERENCES workspace(id),
  worker        TEXT NOT NULL,
  lease_fence   INTEGER NOT NULL,
  attempt_limit INTEGER NOT NULL,
  base_oid      TEXT NOT NULL,
  head_oid      TEXT,
  state         TEXT NOT NULL CHECK (state IN ('active', 'ended')),
  outcome       TEXT,
  ended_at      INTEGER,
  CHECK ((kind = 'objective') = (parent_run_id IS NULL))
) STRICT`,
    `CREATE UNIQUE INDEX run_one_active ON run (node_id) WHERE state = 'active'`,
    `CREATE TABLE attempt (
  id             TEXT PRIMARY KEY,
  run_id         TEXT NOT NULL REFERENCES run(id),
  attempt_no     INTEGER NOT NULL,
  provider_id    TEXT NOT NULL REFERENCES provider(id),
  provider_model TEXT NOT NULL,
  timeout_ms     INTEGER NOT NULL,
  base_oid       TEXT NOT NULL,
  head_oid       TEXT,
  outcome        TEXT CHECK (outcome IS NULL OR outcome IN
                 ('accepted', 'rejected', 'failed', 'timed-out', 'cancelled')),
  ended_at       INTEGER,
  UNIQUE (run_id, attempt_no)
) STRICT`,
    `CREATE TABLE agent_invocation (
  id                    TEXT PRIMARY KEY,
  attempt_id            TEXT NOT NULL REFERENCES attempt(id),
  agent                 TEXT NOT NULL CHECK (agent IN ('general@1', 'swe@1', 'te@1', 're@1')),
  adapter_version       TEXT NOT NULL,
  prompt_blob           TEXT NOT NULL REFERENCES blob(hash),
  sources_json          TEXT NOT NULL,
  tool_definitions_blob TEXT NOT NULL REFERENCES blob(hash),
  tool_trace_blob       TEXT REFERENCES blob(hash),
  diff_blob             TEXT REFERENCES blob(hash),
  verdict               TEXT CHECK (verdict IS NULL OR verdict IN ('accept', 'reject')),
  reason_blob           TEXT REFERENCES blob(hash),
  usage_json            TEXT,
  error_blob            TEXT REFERENCES blob(hash),
  ended_at              INTEGER
) STRICT`,
    `CREATE TABLE candidate (
  id                   TEXT PRIMARY KEY,
  node_id              TEXT NOT NULL REFERENCES node(id),
  run_id               TEXT NOT NULL REFERENCES run(id),
  workspace_id         TEXT NOT NULL REFERENCES workspace(id),
  revision             TEXT NOT NULL,
  candidate_oid        TEXT NOT NULL,
  landing_base_oid     TEXT NOT NULL,
  merge_oid            TEXT,
  projected_outcome    TEXT NOT NULL CHECK (projected_outcome IN ('done', 'partial')),
  evidence_blob        TEXT NOT NULL REFERENCES blob(hash),
  profile_blob         TEXT NOT NULL REFERENCES blob(hash),
  convention_version   TEXT NOT NULL,
  state                TEXT NOT NULL CHECK (state IN ('open', 'approved', 'invalidated')),
  acknowledged_partial INTEGER,
  publish_requested    INTEGER,
  approved_actor       TEXT,
  approved_at          INTEGER,
  invalidated_at       INTEGER,
  invalidated_reason   TEXT,
  updated_at           INTEGER NOT NULL,
  UNIQUE (node_id, revision),
  CHECK (state <> 'approved' OR projected_outcome = 'done' OR acknowledged_partial IS 1)
) STRICT`,
    `CREATE TABLE check_result (
  id                 TEXT PRIMARY KEY,
  subject_kind       TEXT NOT NULL CHECK (subject_kind IN ('candidate', 'merge',
                      'task-diagnostic', 'reconcile', 'profile-gate', 'initiative-e2e')),
  subject_id         TEXT,
  node_id            TEXT REFERENCES node(id),
  run_id             TEXT REFERENCES run(id),
  commit_oid         TEXT,
  manifest_blob      TEXT REFERENCES blob(hash),
  check_name         TEXT NOT NULL,
  command_json       TEXT NOT NULL,
  cwd                TEXT NOT NULL,
  env_identity       TEXT NOT NULL,
  toolchain_version  TEXT NOT NULL,
  timeout_ms         INTEGER NOT NULL,
  authoritative      INTEGER NOT NULL,
  result             TEXT NOT NULL CHECK (result IN ('running', 'passed', 'failed',
                      'error', 'timed-out', 'cancelled', 'not-applicable')),
  exit_code          INTEGER,
  output_blob        TEXT REFERENCES blob(hash),
  profile_blob       TEXT REFERENCES blob(hash),
  convention_version TEXT NOT NULL,
  invalidated_at     INTEGER,
  ended_at           INTEGER,
  CHECK (result = 'not-applicable' OR commit_oid IS NOT NULL OR manifest_blob IS NOT NULL)
) STRICT`,
    `CREATE TABLE git_operation (
  id                  TEXT PRIMARY KEY,
  repository_id       TEXT NOT NULL REFERENCES repository(id),
  intent              TEXT NOT NULL CHECK (intent IN ('merge', 'sync', 'publish', 'revert')),
  node_id             TEXT REFERENCES node(id),
  run_id              TEXT REFERENCES run(id),
  candidate_id        TEXT REFERENCES candidate(id),
  lease_fence         INTEGER NOT NULL,
  ref                 TEXT NOT NULL,
  base_oid            TEXT NOT NULL,
  proposed_head_oid   TEXT NOT NULL,
  result_head_oid     TEXT,
  expected_remote_oid TEXT,
  state               TEXT NOT NULL CHECK (state IN ('open', 'complete', 'discarded')),
  outcome             TEXT,
  detail_blob         TEXT REFERENCES blob(hash),
  child_token         TEXT,
  completed_at        INTEGER
) STRICT`,
    `CREATE TABLE event (
  id           TEXT PRIMARY KEY,
  subject_kind TEXT NOT NULL,
  subject_id   TEXT NOT NULL,
  type         TEXT NOT NULL,
  actor_kind   TEXT NOT NULL CHECK (actor_kind IN ('human', 'daemon')),
  actor_id     TEXT NOT NULL,
  payload_json TEXT NOT NULL
) STRICT`,
  ],
};
